name: 'Detect Rapid Scan Action'
description: 'A GitHub action to perform a Detect rapid scan and record the results'
inputs:
  github-token:
    description: 'Your GitHub token'
    required: true
  blackduck-url:
    description: 'Url of Black Duck instance'
    required: true
  blackduck-api-token:
    description: 'API Token for Black Duck instance'
    required: true
  scan-mode:
    description: 'Either RAPID or INTELLIGENT, configures how Detect is invoked. RAPID will not persist the results and disables select Detect functionality for faster results. INTELLIGENT persists the results and permits all features of Detect.'
    required: false
    default: 'RAPID'
  output-path-override:
    description: 'Override for where to output Detect files, default is $RUNNER_TEMP/blackduck/'
    required: false
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
