name: 'Detect Rapid Scan Action'
description: 'A GitHub action to perform a Detect rapid scan and record the results'
inputs:
  github-token:
    description: 'Your GitHub token'
    required: true
  detect-version:
    description: 'The version of Detect to download'
    required: true
  blackduck-url:
    description: 'Url of Black Duck instance'
    required: true
  blackduck-api-token:
    description: 'API Token for Black Duck instance'
    required: true
  scan-mode:
    description: 'Either RAPID or INTELLIGENT, configures how Detect is invoked. RAPID will not persist the results and disables select Detect functionality for faster results. INTELLIGENT persists the results and permits all features of Detect.'
    required: false
    default: 'RAPID'
  output-path-override:
    description: 'Override for where to output Detect files, default is $RUNNER_TEMP/blackduck/'
    required: false
  detect-trust-cert:
    description: 'Acceptable Values: TRUE, FALSE. If TRUE, Detect will trust the Black Duck certificate even if the certificate is not in the keystore.'
    default: 'TRUE'
  fail-on-severities:
    description: 'Acceptable Values: ALL, NONE, BLOCKER, CRITICAL, MAJOR, MINOR, OK, TRIVIAL, UNSPECIFIED. Fail on Policy Violation Severities: A comma-separated list of policy violation severities that will fail Detect. If this is set to NONE, Detect will not fail due to policy violations. A value of ALL is equivalent to all of the other possible values except NONE.'
    required: false
    default: 'BLOCKER,CRITICAL,MAJOR'
runs:
  using: 'node12'
  main: 'dist/index.js'
